server:
  port: 9090
spring:
  cloud:
    function:
      definition: uppercase|reverse
    stream:
      binders:
        #This section of the configuration tells the solace binder how to connect to the solace event broker/mesh
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcps://solacehost:55443
                msgVpn: spring-cloud-stream
                clientUsername: username
                clientPassword: password
                connectRetries: 3
                connectRetriesPerHost: 0
                reconnectRetries: 3
      function:
        bindings:
          uppercasereverse-in-0: input
          uppercasereverse-out-0: output